### ISSUE TITLE
Условия задачи

### ISSUE THREAD

**Issue by coursar** [ShaidVL/homework_cashback#1]
По условиям, у функции было три параметра:
1. Траты по обычной категории бонусов
2. Траты по повышенной категории бонусов
3. Траты по премиальной категории бонусов

**Comment by ShaidVL** [comment]
@coursar я не понял условия, на вход три массива подавать что-ли?
И еще вопрос, когда я ишью закрываю, Вы это видите? или мне надо как-то оповестить, чтобы Вы проверили

**Comment by coursar** [comment]
1. Нет, три числа
2. Вижу
